import type { Metadata } from "next";
import clashGrotesk from 'next/font/local';
import  "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = clashGrotesk({
  src: '../../public/fonts/ClashGrotesk-Regular.ttf',
  display: 'swap',
})

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={myFont.className}>{children}</body>
      </html>
  );
}
